import type { NextPage } from 'next'
import Head from 'next/head'
import { ContentManager, ContentViewer } from '@components/index'
import { useContentEditionContext } from '@contexts/ContentEditionContext'

const Home: NextPage = () => {
  const { blocks } = useContentEditionContext()

  return (
    <div className="">
      <Head>
        <title>React Page Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <ContentViewer blocks={blocks} />
        <ContentManager />
      </main>
    </div>
  )
}

export default Home
